/**
 * Définition des symbols
 * Romain Pelletier & Arthur Delrue
*/

#include "symbol.h"

Symbol symbol_new(char* id_name)
{
	Symbol  symbol = malloc(sizeof(symbol_t));
	
	if(symbol == NULL)
		return NULL;
	
	symbol->name = id_name;
	symbol->data_type = NotDefine;
	symbol->state = NotInitialized;
	
	return symbol;
}

Symbol symbol_new_integer(char* id_name)
{
	Symbol  symbol = symbol_new(id_name);
	
	if(symbol == NULL)
		return NULL;
	
	symbol->data_type = Integer;
	return symbol;
}

Symbol symbol_new_integer_init(char* id_name, int number)
{
	Symbol  symbol = symbol_new_integer(id_name);
	
	if(symbol == NULL)
		return NULL;
	symbol->state = Initialized;
	symbol->data.number = number;
	
	return symbol;
}

Symbol symbol_new_constant (char* id_name, int number)
{
	Symbol  symbol = symbol_new_integer_init(id_name, number);

	if(symbol != NULL)
		symbol->data_type = Constant;

	return symbol;
}

Symbol symbol_new_string (char* id_name, char* string)
{
	Symbol  symbol = symbol_new(id_name);
	
	if(symbol == NULL)
		return NULL;
	
	symbol->data_type = String;
	symbol->state = Initialized;
	symbol->data.string = string;
	return symbol;
	
}

Symbol symbol_new_stencil (char* id_name)
{
	Symbol  symbol = symbol_new(id_name);
	
	if(symbol == NULL)
		return NULL;
		
	symbol->data_type = Stencil;
	
	return symbol;
}

Symbol symbol_new_stencil_init(char* id_name,Array array_data)
{
	Symbol  symbol = symbol_new_stencil(id_name);
	
	if(symbol == NULL)
		return NULL;
		
	symbol->state = Initialized;
	symbol->data.array = array_data;
	
	return symbol;
}

Symbol symbol_new_array(char* id_name)
{
	Symbol  symbol = symbol_new(id_name);
	
	if(symbol == NULL)
		return NULL;
	
	symbol->data_type = Arraytype;
	
	return symbol;
}

Symbol symbol_new_array_init(char* id_name, Array array_data)
{
	Symbol  symbol = symbol_new_array(id_name);
	
	if(symbol == NULL)
		return NULL;
		
	symbol->state = Initialized;
	symbol->data.array = array_data;
	
	return symbol;
}


bool is_constant_symbol(Symbol symbol)
{
	if(symbol && symbol->data_type == Constant)
		return true;
	
	return false;
}

bool is_integer_symbol(Symbol symbol)
{
	if(symbol && symbol->data_type == Integer)
		return true;
	
	return false;
}

bool is_string_symbol(Symbol symbol)
{
	if(symbol && symbol->data_type == String)
		return true;
	
	return false;
}

bool is_stencil_symbol(Symbol symbol)
{
	if(symbol && symbol->data_type == Stencil)
		return true;
	
	return false;
}

bool is_array_symbol(Symbol symbol)
{
	if(symbol && symbol->data_type == Arraytype)
		return true;
	
	return false;
}


Symbol symbol_lookup(Symbol list_symbol, char* id_name)
{
	Symbol tmp_symbol = list_symbol;
	while(tmp_symbol != NULL){
		
		if(strcmp(id_name, tmp_symbol->name) == 0)
			return tmp_symbol;
		
		tmp_symbol = tmp_symbol->successor;
	}
	return tmp_symbol;
}

void symbol_print(Symbol symbol)
{
	if(symbol == NULL)
		return;
	
	if(symbol->name != NULL)
		printf("\t %s :",symbol->name);
	
	switch(symbol->data_type)
	{
		case Constant: printf("%d\t [Const]\n", symbol->data.number);
			break;
		case Integer: printf("%d\t [Integer]\n", symbol->data.number);
			break;
		case String: printf("%s\t [String]\n", symbol->data.string);
			break;
		case Arraytype: printf("\t Array \n");
				if(symbol->data.array->dim_values!= NULL)
				{
					printf("\t\tDimension Values :  ");
					list_print(symbol->data.array->dim_values);
				}
				printf("\t\tArray elemets:  ");
				if(symbol->data.array->element_list!= NULL)
				{
					list_print(symbol->data.array->element_list);
				}
				else
					printf("Array elemets :  Not initialized\n");
			break;
		case Stencil: printf("\tStencil\n");
					printf("\t\t Number of elements : %d\n",symbol->data.array->elements_number);
					printf("\t\tStencil elemets:  ");
					list_print(symbol->data.array->element_list);
			break;
		case Procedure: printf("Procedure\n");
			break;
	}
	symbol_print(symbol->successor);	
	
}

void symbol_print_code(Symbol symbol, FILE* output_file, DataType data_type)
{
	Symbol tmp_symbol = symbol;
	
	while(tmp_symbol != NULL)
	{
		if(tmp_symbol->data_type == data_type)
		{
			
			if(tmp_symbol->data_type == Constant)
			{
				// don't print constant number generated by the parsing
			  if(strstr(tmp_symbol->name, CONSTANT_) != NULL)
			  {
				tmp_symbol = tmp_symbol->successor;
				continue ;
			  }
			  fprintf(output_file, "\t%s: \t%d\n", tmp_symbol->name, tmp_symbol->data.number);
			  
			}
			
			else if(tmp_symbol->data_type == Integer)
				fprintf(output_file, "\t%s:\t.word\t%d\n", tmp_symbol->name, tmp_symbol->data.number);
			
			else if(tmp_symbol->data_type == String)
				fprintf(output_file, "\t%s:\t.asciiz\t\"%s\"\n", tmp_symbol->name, tmp_symbol->data.string);
			
			else if(tmp_symbol->data_type == Arraytype)
				{
					if(tmp_symbol->state == NotInitialized)
					{
						fprintf(output_file, "\t%s:\t.space\t%d\n", tmp_symbol->name, tmp_symbol->data.array->elements_number*4);
						fprintf(output_file, "\t%s%s:\t%d\n", TAILLE_, tmp_symbol->name,tmp_symbol->data.array->elements_number);
						tmp_symbol = tmp_symbol->successor;
						continue;
					}
					
					fprintf(output_file, "\t%s:\t.word\t", tmp_symbol->name);
					ArrayElement arraylist_tmp = tmp_symbol->data.array->element_list->head;
					int nb_par_ligne = 0;
					while(arraylist_tmp!=NULL)
					{
						fprintf(output_file,"%d", arraylist_tmp->value);
						if(arraylist_tmp->next != NULL)
						{
							if(nb_par_ligne<10)
								fprintf(output_file,", ");
							else
								fprintf(output_file,"\t\t.word\t");
						}
						else 
							fprintf(output_file,"\n");
						arraylist_tmp = arraylist_tmp->next;
					}
					fprintf(output_file, "\t%s%s:\t%d\n", TAILLE_, tmp_symbol->name,tmp_symbol->data.array->elements_number);
				}
			else if(tmp_symbol->data_type == Stencil)
				{
					fprintf(output_file, "\t%s:\t.word\t", tmp_symbol->name);
					ArrayElement arraylist_tmp = tmp_symbol->data.array->element_list->head;
					int nb_par_ligne = 0;
					while(arraylist_tmp!=NULL)
					{
						fprintf(output_file,"%d", arraylist_tmp->value);
						if(arraylist_tmp->next != NULL)
						{
							if(nb_par_ligne<10)
								fprintf(output_file,", ");
							else
								fprintf(output_file,"\t\t.word\t");
						}
						else 
							fprintf(output_file,"\n");
						arraylist_tmp = arraylist_tmp->next;
					}
					fprintf(output_file, "\t%s%s:\t%d\n", TAILLE_, tmp_symbol->name,tmp_symbol->data.array->elements_number);
				}
		}
		
		tmp_symbol = tmp_symbol->successor;
	}
}


void symbol_free(Symbol symbol)
{
	if(symbol == NULL)
		return;
	
	if(symbol->name != NULL)
		free(symbol->name);
		symbol->name = NULL;
	
		switch(symbol->data_type)
		{
			case String: free(symbol->data.string);
						symbol->data.string = NULL;
						break;
			case Arraytype: array_free(symbol->data.array);
						symbol->data.array = NULL;
						break;
			case Stencil: array_free(symbol->data.array); 
						symbol->data.array = NULL;
						break;
		}
	
	free(symbol);
	return;
}
